@baseUrl = http://localhost:5000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODgzNTQyOTYwMDQzN2MwNjc2NWY1ZDEiLCJpYXQiOjE3NTM3ODY0MjMsImV4cCI6MTc1NTA4MjQyM30.dRty9opHACgf001-9PaI1Zu2bMMi3fjZ-bkZGgM3e5c

### Create a package list
POST {{baseUrl}}/package-lists
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "White T-Shirt"
}


### Get all package lists
GET {{baseUrl}}/package-lists/
Authorization: Bearer {{token}}


### Get a package list by id
GET {{baseUrl}}/package-lists/6880c2975239c5d602c485bd
Authorization: Bearer {{token}}

### Update a package list
PATCH {{baseUrl}}/package-lists/6888a8c4c70ed0c9619facb5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "completed": true
}

### Delete a package list
DELETE {{baseUrl}}/package-lists/6880c2975239c5d602c485bd
Authorization: Bearer {{token}}

### Create a user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe2@gmail.com",
  "password": "password"
}

### Register a user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe2@gmail.com",
  "password": "password"
}

### Login a user
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john.doe2@gmail.com",
  "password": "password"
}

### Create a trip
POST {{baseUrl}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Pokhara, Mustang and Manakamana",
  "startDate": "2025-08-11",
  "endDate": "2025-08-11",
  "destinations": ["Pokhara", "Jomsom", "Muktinath", "Manakamana"],
  "budget": {
    "total": 50000,
    "spent": 0
  }
}

### Get all trips
GET {{baseUrl}}/trips
Authorization: Bearer {{token}}

### Get a trip by id
GET {{baseUrl}}/trips/6889f237ea517db3436eb505
Authorization: Bearer {{token}}

### Add an expense to a trip
POST {{baseUrl}}/trips/6889f237ea517db3436eb505/expenses
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2025-08-11",
  "amount": 1200,
  "name": "Taxi Fare"
}

### Create an itinerary
POST {{baseUrl}}/itineraries/6889f237ea517db3436eb506
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "tripId": "6889f237ea517db3436eb505",
  "title": "Day 1",
  "description": "This is a description of the itinerary Day 1",
  "date": "2025-07-31",
  "activities": [
    {
      "name": "Check in at Hotel",
      "time": "08:00 AM",
      "notes": ["Check In", "Breakfast", "Rest"]
    },
    {
      "name": "Visit Lake Side",
      "time": "11:00 AM - 02:00 PM",
      "notes": ["Visit Lake Side", "Tal Barahi Temple", "Do Boating", "Click Pictures"]
    },
    {
      "name": "Visit Street 9",
      "time": "02:00 PM - 03:00 PM",
      "notes": ["Have Lunch", "Hire a Cab"]
    }
  ]
}

### Invite a collaborator to a trip
POST {{baseUrl}}/trips/688b489d79c3e839f6cf0c4f/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": ["cloveit2024@gmail.com"]
}

### Accept an invitation to a trip
GET {{baseUrl}}/trips/6889f237ea517db3436eb505/invite/accept?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0cmlwSWQiOiI2ODg5ZjIzN2VhNTE3ZGIzNDM2ZWI1MDUiLCJpYXQiOjE3NTQ1NjQwMTksImV4cCI6MTc1NDU2NzYxOX0.r3w2wFt_hMAswEPUcecP2YROL2itUmiJCtYwszflk1k
Authorization: Bearer {{token}}

