@baseUrl = http://localhost:5000

### Create a package list
POST {{baseUrl}}/package-lists
Content-Type: application/json

{
  "name": "Trousers"
}

### Get all package lists
GET {{baseUrl}}/package-lists


### Get a package list by id
GET {{baseUrl}}/package-lists/687e106cc7d7b72a4b0e7e0b