@baseUrl = http://localhost:5000

### Create a package list
POST {{baseUrl}}/package-lists
Content-Type: application/json

{
  "name": "Trousers"
}

### Get all package lists
GET {{baseUrl}}/package-lists/


### Get a package list by id
GET {{baseUrl}}/package-lists/

### Update a package list
PATCH {{baseUrl}}/package-lists/687e106cc7d7b72a4b0e7e0a
Content-Type: application/json

{
  "completed": true
}

### Delete a package list
DELETE {{baseUrl}}/package-lists/687e107cc7d7b72a4b0e7e0d

### Create a user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe2",
  "password": "password"
}